FROM openjdk:11-jdk-slim

COPY ./target/User-microservice-0.0.1-SNAPSHOT.jar /usr/src/User-microservice/
WORKDIR /usr/src/User-microservice
EXPOSE 8083
CMD ["java", "-jar", "User-microservice-0.0.1-SNAPSHOT.jar"]
