// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system-events.proto

package com.example.systemevents;

public final class OuterClass {
  private OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>string nazivMikroservisa = 2;</code>
     */
    java.lang.String getNazivMikroservisa();
    /**
     * <code>string nazivMikroservisa = 2;</code>
     */
    com.google.protobuf.ByteString
        getNazivMikroservisaBytes();

    /**
     * <code>.Request.tipAkcije tip = 4;</code>
     */
    int getTipValue();
    /**
     * <code>.Request.tipAkcije tip = 4;</code>
     */
    OuterClass.Request.tipAkcije getTip();

    /**
     * <code>string nazivResursa = 5;</code>
     */
    java.lang.String getNazivResursa();
    /**
     * <code>string nazivResursa = 5;</code>
     */
    com.google.protobuf.ByteString
        getNazivResursaBytes();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      nazivMikroservisa_ = "";
      tip_ = 0;
      nazivResursa_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nazivMikroservisa_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              tip_ = rawValue;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              nazivResursa_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OuterClass.internal_static_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OuterClass.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OuterClass.Request.class, OuterClass.Request.Builder.class);
    }

    /**
     * Protobuf enum {@code Request.tipAkcije}
     */
    public enum tipAkcije
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GET = 0;</code>
       */
      GET(0),
      /**
       * <code>UPDATE = 1;</code>
       */
      UPDATE(1),
      /**
       * <code>CREATE = 2;</code>
       */
      CREATE(2),
      /**
       * <code>DELETE = 3;</code>
       */
      DELETE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>GET = 0;</code>
       */
      public static final int GET_VALUE = 0;
      /**
       * <code>UPDATE = 1;</code>
       */
      public static final int UPDATE_VALUE = 1;
      /**
       * <code>CREATE = 2;</code>
       */
      public static final int CREATE_VALUE = 2;
      /**
       * <code>DELETE = 3;</code>
       */
      public static final int DELETE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static tipAkcije valueOf(int value) {
        return forNumber(value);
      }

      public static tipAkcije forNumber(int value) {
        switch (value) {
          case 0: return GET;
          case 1: return UPDATE;
          case 2: return CREATE;
          case 3: return DELETE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<tipAkcije>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          tipAkcije> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<tipAkcije>() {
              public tipAkcije findValueByNumber(int number) {
                return tipAkcije.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return OuterClass.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final tipAkcije[] VALUES = values();

      public static tipAkcije valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private tipAkcije(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Request.tipAkcije)
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    public static final int NAZIVMIKROSERVISA_FIELD_NUMBER = 2;
    private volatile java.lang.Object nazivMikroservisa_;
    /**
     * <code>string nazivMikroservisa = 2;</code>
     */
    public java.lang.String getNazivMikroservisa() {
      java.lang.Object ref = nazivMikroservisa_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nazivMikroservisa_ = s;
        return s;
      }
    }
    /**
     * <code>string nazivMikroservisa = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNazivMikroservisaBytes() {
      java.lang.Object ref = nazivMikroservisa_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nazivMikroservisa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIP_FIELD_NUMBER = 4;
    private int tip_;
    /**
     * <code>.Request.tipAkcije tip = 4;</code>
     */
    public int getTipValue() {
      return tip_;
    }
    /**
     * <code>.Request.tipAkcije tip = 4;</code>
     */
    public OuterClass.Request.tipAkcije getTip() {
      OuterClass.Request.tipAkcije result = OuterClass.Request.tipAkcije.valueOf(tip_);
      return result == null ? OuterClass.Request.tipAkcije.UNRECOGNIZED : result;
    }

    public static final int NAZIVRESURSA_FIELD_NUMBER = 5;
    private volatile java.lang.Object nazivResursa_;
    /**
     * <code>string nazivResursa = 5;</code>
     */
    public java.lang.String getNazivResursa() {
      java.lang.Object ref = nazivResursa_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nazivResursa_ = s;
        return s;
      }
    }

    public com.google.protobuf.ByteString
        getNazivResursaBytes() {
      java.lang.Object ref = nazivResursa_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nazivResursa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != null) {
        output.writeMessage(1, getTimestamp());
      }
      if (!getNazivMikroservisaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nazivMikroservisa_);
      }
      if (tip_ != OuterClass.Request.tipAkcije.GET.getNumber()) {
        output.writeEnum(4, tip_);
      }
      if (!getNazivResursaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nazivResursa_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTimestamp());
      }
      if (!getNazivMikroservisaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nazivMikroservisa_);
      }
      if (tip_ != OuterClass.Request.tipAkcije.GET.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, tip_);
      }
      if (!getNazivResursaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nazivResursa_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OuterClass.Request)) {
        return super.equals(obj);
      }
      OuterClass.Request other = (OuterClass.Request) obj;

      boolean result = true;
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && getTimestamp()
            .equals(other.getTimestamp());
      }
      result = result && getNazivMikroservisa()
          .equals(other.getNazivMikroservisa());
      result = result && tip_ == other.tip_;
      result = result && getNazivResursa()
          .equals(other.getNazivResursa());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (37 * hash) + NAZIVMIKROSERVISA_FIELD_NUMBER;
      hash = (53 * hash) + getNazivMikroservisa().hashCode();
      hash = (37 * hash) + TIP_FIELD_NUMBER;
      hash = (53 * hash) + tip_;
      hash = (37 * hash) + NAZIVRESURSA_FIELD_NUMBER;
      hash = (53 * hash) + getNazivResursa().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OuterClass.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OuterClass.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OuterClass.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OuterClass.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OuterClass.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OuterClass.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OuterClass.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OuterClass.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OuterClass.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OuterClass.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OuterClass.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OuterClass.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OuterClass.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        OuterClass.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OuterClass.internal_static_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OuterClass.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OuterClass.Request.class, OuterClass.Request.Builder.class);
      }

      // Construct using com.example.systemevents.OuterClass.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        nazivMikroservisa_ = "";

        tip_ = 0;

        nazivResursa_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OuterClass.internal_static_Request_descriptor;
      }

      public OuterClass.Request getDefaultInstanceForType() {
        return OuterClass.Request.getDefaultInstance();
      }

      public OuterClass.Request build() {
        OuterClass.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OuterClass.Request buildPartial() {
        OuterClass.Request result = new OuterClass.Request(this);
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        result.nazivMikroservisa_ = nazivMikroservisa_;
        result.tip_ = tip_;
        result.nazivResursa_ = nazivResursa_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OuterClass.Request) {
          return mergeFrom((OuterClass.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OuterClass.Request other) {
        if (other == OuterClass.Request.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (!other.getNazivMikroservisa().isEmpty()) {
          nazivMikroservisa_ = other.nazivMikroservisa_;
          onChanged();
        }
        if (other.tip_ != 0) {
          setTipValue(other.getTipValue());
        }
        if (!other.getNazivResursa().isEmpty()) {
          nazivResursa_ = other.nazivResursa_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OuterClass.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OuterClass.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private java.lang.Object nazivMikroservisa_ = "";
      /**
       * <code>string nazivMikroservisa = 2;</code>
       */
      public java.lang.String getNazivMikroservisa() {
        java.lang.Object ref = nazivMikroservisa_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nazivMikroservisa_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nazivMikroservisa = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNazivMikroservisaBytes() {
        java.lang.Object ref = nazivMikroservisa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nazivMikroservisa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nazivMikroservisa = 2;</code>
       */
      public Builder setNazivMikroservisa(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nazivMikroservisa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nazivMikroservisa = 2;</code>
       */
      public Builder clearNazivMikroservisa() {
        
        nazivMikroservisa_ = getDefaultInstance().getNazivMikroservisa();
        onChanged();
        return this;
      }
      /**
       * <code>string nazivMikroservisa = 2;</code>
       */
      public Builder setNazivMikroservisaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nazivMikroservisa_ = value;
        onChanged();
        return this;
      }

      private int tip_ = 0;
      /**
       * <code>.Request.tipAkcije tip = 4;</code>
       */
      public int getTipValue() {
        return tip_;
      }
      /**
       * <code>.Request.tipAkcije tip = 4;</code>
       */
      public Builder setTipValue(int value) {
        tip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Request.tipAkcije tip = 4;</code>
       */
      public OuterClass.Request.tipAkcije getTip() {
        OuterClass.Request.tipAkcije result = OuterClass.Request.tipAkcije.valueOf(tip_);
        return result == null ? OuterClass.Request.tipAkcije.UNRECOGNIZED : result;
      }
      /**
       * <code>.Request.tipAkcije tip = 4;</code>
       */
      public Builder setTip(OuterClass.Request.tipAkcije value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        tip_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Request.tipAkcije tip = 4;</code>
       */
      public Builder clearTip() {
        
        tip_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nazivResursa_ = "";
      /**
       * <code>string nazivResursa = 5;</code>
       */
      public java.lang.String getNazivResursa() {
        java.lang.Object ref = nazivResursa_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nazivResursa_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nazivResursa = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNazivResursaBytes() {
        java.lang.Object ref = nazivResursa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nazivResursa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nazivResursa = 5;</code>
       */
      public Builder setNazivResursa(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nazivResursa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nazivResursa = 5;</code>
       */
      public Builder clearNazivResursa() {
        
        nazivResursa_ = getDefaultInstance().getNazivResursa();
        onChanged();
        return this;
      }
      /**
       * <code>string nazivResursa = 5;</code>
       */
      public Builder setNazivResursaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nazivResursa_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final OuterClass.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OuterClass.Request();
    }

    public static OuterClass.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public OuterClass.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string odgovorNaAkciju = 1;</code>
     */
    java.lang.String getOdgovorNaAkciju();
    /**
     * <code>string odgovorNaAkciju = 1;</code>
     */
    com.google.protobuf.ByteString
        getOdgovorNaAkcijuBytes();

    /**
     * <code>.Response.tipOdgovoraNaAkciju tip = 2;</code>
     */
    int getTipValue();
    /**
     * <code>.Response.tipOdgovoraNaAkciju tip = 2;</code>
     */
    OuterClass.Response.tipOdgovoraNaAkciju getTip();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      odgovorNaAkciju_ = "";
      tip_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              odgovorNaAkciju_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              tip_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OuterClass.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OuterClass.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OuterClass.Response.class, OuterClass.Response.Builder.class);
    }

    /**
     * Protobuf enum {@code Response.tipOdgovoraNaAkciju}
     */
    public enum tipOdgovoraNaAkciju
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0),
      /**
       * <code>ERROR = 1;</code>
       */
      ERROR(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>ERROR = 1;</code>
       */
      public static final int ERROR_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static tipOdgovoraNaAkciju valueOf(int value) {
        return forNumber(value);
      }

      public static tipOdgovoraNaAkciju forNumber(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<tipOdgovoraNaAkciju>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          tipOdgovoraNaAkciju> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<tipOdgovoraNaAkciju>() {
              public tipOdgovoraNaAkciju findValueByNumber(int number) {
                return tipOdgovoraNaAkciju.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return OuterClass.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final tipOdgovoraNaAkciju[] VALUES = values();

      public static tipOdgovoraNaAkciju valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private tipOdgovoraNaAkciju(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Response.tipOdgovoraNaAkciju)
    }

    public static final int ODGOVORNAAKCIJU_FIELD_NUMBER = 1;
    private volatile java.lang.Object odgovorNaAkciju_;
    /**
     * <code>string odgovorNaAkciju = 1;</code>
     */
    public java.lang.String getOdgovorNaAkciju() {
      java.lang.Object ref = odgovorNaAkciju_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        odgovorNaAkciju_ = s;
        return s;
      }
    }
    /**
     * <code>string odgovorNaAkciju = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOdgovorNaAkcijuBytes() {
      java.lang.Object ref = odgovorNaAkciju_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        odgovorNaAkciju_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIP_FIELD_NUMBER = 2;
    private int tip_;
    /**
     * <code>.Response.tipOdgovoraNaAkciju tip = 2;</code>
     */
    public int getTipValue() {
      return tip_;
    }
    /**
     * <code>.Response.tipOdgovoraNaAkciju tip = 2;</code>
     */
    public OuterClass.Response.tipOdgovoraNaAkciju getTip() {
      OuterClass.Response.tipOdgovoraNaAkciju result = OuterClass.Response.tipOdgovoraNaAkciju.valueOf(tip_);
      return result == null ? OuterClass.Response.tipOdgovoraNaAkciju.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOdgovorNaAkcijuBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, odgovorNaAkciju_);
      }
      if (tip_ != OuterClass.Response.tipOdgovoraNaAkciju.SUCCESS.getNumber()) {
        output.writeEnum(2, tip_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOdgovorNaAkcijuBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, odgovorNaAkciju_);
      }
      if (tip_ != OuterClass.Response.tipOdgovoraNaAkciju.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, tip_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OuterClass.Response)) {
        return super.equals(obj);
      }
      OuterClass.Response other = (OuterClass.Response) obj;

      boolean result = true;
      result = result && getOdgovorNaAkciju()
          .equals(other.getOdgovorNaAkciju());
      result = result && tip_ == other.tip_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ODGOVORNAAKCIJU_FIELD_NUMBER;
      hash = (53 * hash) + getOdgovorNaAkciju().hashCode();
      hash = (37 * hash) + TIP_FIELD_NUMBER;
      hash = (53 * hash) + tip_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OuterClass.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OuterClass.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OuterClass.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OuterClass.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OuterClass.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OuterClass.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OuterClass.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OuterClass.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OuterClass.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OuterClass.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OuterClass.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        OuterClass.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OuterClass.internal_static_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OuterClass.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OuterClass.Response.class, OuterClass.Response.Builder.class);
      }

      // Construct using com.example.systemevents.OuterClass.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        odgovorNaAkciju_ = "";

        tip_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OuterClass.internal_static_Response_descriptor;
      }

      public OuterClass.Response getDefaultInstanceForType() {
        return OuterClass.Response.getDefaultInstance();
      }

      public OuterClass.Response build() {
        OuterClass.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OuterClass.Response buildPartial() {
        OuterClass.Response result = new OuterClass.Response(this);
        result.odgovorNaAkciju_ = odgovorNaAkciju_;
        result.tip_ = tip_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OuterClass.Response) {
          return mergeFrom((OuterClass.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OuterClass.Response other) {
        if (other == OuterClass.Response.getDefaultInstance()) return this;
        if (!other.getOdgovorNaAkciju().isEmpty()) {
          odgovorNaAkciju_ = other.odgovorNaAkciju_;
          onChanged();
        }
        if (other.tip_ != 0) {
          setTipValue(other.getTipValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OuterClass.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OuterClass.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object odgovorNaAkciju_ = "";
      /**
       * <code>string odgovorNaAkciju = 1;</code>
       */
      public java.lang.String getOdgovorNaAkciju() {
        java.lang.Object ref = odgovorNaAkciju_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          odgovorNaAkciju_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string odgovorNaAkciju = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOdgovorNaAkcijuBytes() {
        java.lang.Object ref = odgovorNaAkciju_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          odgovorNaAkciju_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string odgovorNaAkciju = 1;</code>
       */
      public Builder setOdgovorNaAkciju(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        odgovorNaAkciju_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string odgovorNaAkciju = 1;</code>
       */
      public Builder clearOdgovorNaAkciju() {
        
        odgovorNaAkciju_ = getDefaultInstance().getOdgovorNaAkciju();
        onChanged();
        return this;
      }
      /**
       * <code>string odgovorNaAkciju = 1;</code>
       */
      public Builder setOdgovorNaAkcijuBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        odgovorNaAkciju_ = value;
        onChanged();
        return this;
      }

      private int tip_ = 0;
      /**
       * <code>.Response.tipOdgovoraNaAkciju tip = 2;</code>
       */
      public int getTipValue() {
        return tip_;
      }
      /**
       * <code>.Response.tipOdgovoraNaAkciju tip = 2;</code>
       */
      public Builder setTipValue(int value) {
        tip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Response.tipOdgovoraNaAkciju tip = 2;</code>
       */
      public OuterClass.Response.tipOdgovoraNaAkciju getTip() {
        OuterClass.Response.tipOdgovoraNaAkciju result = OuterClass.Response.tipOdgovoraNaAkciju.valueOf(tip_);
        return result == null ? OuterClass.Response.tipOdgovoraNaAkciju.UNRECOGNIZED : result;
      }
      /**
       * <code>.Response.tipOdgovoraNaAkciju tip = 2;</code>
       */
      public Builder setTip(OuterClass.Response.tipOdgovoraNaAkciju value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        tip_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Response.tipOdgovoraNaAkciju tip = 2;</code>
       */
      public Builder clearTip() {
        
        tip_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final OuterClass.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OuterClass.Response();
    }

    public static OuterClass.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public OuterClass.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023system-events.proto\032\037google/protobuf/t" +
      "imestamp.proto\"\304\001\n\007Request\022-\n\ttimestamp\030" +
      "\001 \001(\0132\032.google.protobuf.Timestamp\022\031\n\021naz" +
      "ivMikroservisa\030\002 \001(\t\022\037\n\003tip\030\004 \001(\0162\022.Requ" +
      "est.tipAkcije\022\024\n\014nazivResursa\030\005 \001(\t\"8\n\tt" +
      "ipAkcije\022\007\n\003GET\020\000\022\n\n\006UPDATE\020\001\022\n\n\006CREATE\020" +
      "\002\022\n\n\006DELETE\020\003\"~\n\010Response\022\027\n\017odgovorNaAk" +
      "ciju\030\001 \001(\t\022*\n\003tip\030\002 \001(\0162\035.Response.tipOd" +
      "govoraNaAkciju\"-\n\023tipOdgovoraNaAkciju\022\013\n" +
      "\007SUCCESS\020\000\022\t\n\005ERROR\020\0012.\n\014SystemEvents\022\036\n",
      "\005start\022\010.Request\032\t.Response\"\000B\032\n\030com.exa" +
      "mple.systemeventsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "Timestamp", "NazivMikroservisa", "Tip", "NazivResursa", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "OdgovorNaAkciju", "Tip", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
